import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import AnalyticsProvider from "./analytics-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AdMaker AI | Create AI Ads in Minutes",
  description: "The #1 platform to create AI video ads. Write your script, choose your actors, and generate your video in 2 minutes.",
  alternates: {
    canonical: "https://admakerai.app/",
    languages: {
      'en': "https://admakerai.app/",
      'fr': "https://admakerai.app/fr",
      'es': "https://admakerai.app/es",
      'pt': "https://admakerai.app/pt",
      'ko': "https://admakerai.app/ko",
      'de': "https://admakerai.app/de",
      'ja': "https://admakerai.app/ja",
      'x-default': "https://admakerai.app/",
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Note: CSRF token is automatically generated by middleware when needed
  // We don't set it here because cookies can only be modified in Server Actions or Route Handlers

  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleAnalytics />
        <AnalyticsProvider />
        {children}
        <Footer />
      </body>
    </html>
  );
}
