import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import AnalyticsProvider from "./analytics-provider";
import { Suspense } from "react";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-inter',
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-jakarta',
});

export const metadata: Metadata = {
  title: "AdMaker AI | Create AI Ads in Minutes",
  description: "The #1 platform to create AI video ads. Write your script, choose your actors, and generate your video in 2 minutes.",
  icons: {
    icon: 'https://admakerai.app/favicon.ico',
    shortcut: 'https://admakerai.app/favicon.ico',
    apple: 'https://admakerai.app/favicon.ico',
  },
  alternates: {
    canonical: "https://admakerai.app/",
    languages: {
      'en': "https://admakerai.app/",
      'fr': "https://admakerai.app/fr",
      'es': "https://admakerai.app/es",
      'pt': "https://admakerai.app/pt",
      'ko': "https://admakerai.app/ko",
      'de': "https://admakerai.app/de",
      'ja': "https://admakerai.app/ja",
      'x-default': "https://admakerai.app/",
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Note: CSRF token is automatically generated by middleware when needed
  // We don't set it here because cookies can only be modified in Server Actions or Route Handlers

  return (
    <html lang="en">
      <head>
        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ff0844" />
        {/* Preconnect to external domains for faster resource loading */}
        <link rel="preconnect" href="https://images.unsplash.com" />
        <link rel="preconnect" href="https://pub-02bf1ac6244444b5810b067310ef4874.r2.dev" />
        <link rel="dns-prefetch" href="https://images.unsplash.com" />
        <link rel="dns-prefetch" href="https://pub-02bf1ac6244444b5810b067310ef4874.r2.dev" />
        {/* Preload critical logo image */}
        <link
          rel="preload"
          href="https://pub-02bf1ac6244444b5810b067310ef4874.r2.dev/admaker_ai_logo-removebg-preview.png"
          as="image"
        />
        {/* Register Service Worker */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/sw.js').catch(function(err) {
                    console.log('SW registration failed:', err);
                  });
                });
              }
            `,
          }}
        />
      </head>
      <body className={`${inter.variable} ${plusJakartaSans.variable} font-sans`}>
        <GoogleAnalytics />
        <Suspense fallback={null}>
          <AnalyticsProvider />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
