import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AdMaker AI | Create AI Ads in Minutes",
  description: "The #1 platform to create AI video ads. Write your script, choose your actors, and generate your video in 2 minutes.",
  icons: {
    icon: "https://pub-e75d3f83986f4cb6b3f1d1d8f8a8c214.r2.dev/logo%20favicon.png",
    shortcut: "https://pub-e75d3f83986f4cb6b3f1d1d8f8a8c214.r2.dev/logo%20favicon.png",
    apple: "https://pub-e75d3f83986f4cb6b3f1d1d8f8a8c214.r2.dev/logo%20favicon.png",
  },
  alternates: {
    canonical: "https://admakerai.app/",
    languages: {
      'en': "https://admakerai.app/",
      'fr': "https://admakerai.app/fr",
      'es': "https://admakerai.app/es",
      'pt': "https://admakerai.app/pt",
      'ko': "https://admakerai.app/ko",
      'de': "https://admakerai.app/de",
      'ja': "https://admakerai.app/ja",
      'x-default': "https://admakerai.app/",
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Note: CSRF token is automatically generated by middleware when needed
  // We don't set it here because cookies can only be modified in Server Actions or Route Handlers

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
